### ISSUE TITLE
Pointing Error Plot

### ISSUE THREAD

**Issue by liweihung** [liweihung/nightskies#5]
Add the plot showing the point error as a function of image number. Make the pipeline automatically save this plot as one of the end products. Make something similar to this plot for example. 

![image](https://user-images.githubusercontent.com/15639514/32123727-852c2bc0-bb22-11e7-82dd-d89f8b7646d6.png)

**Comment by dbetchkal** [comment]
@liweihung, I'm revisiting this today.  

I see the variable `pterr` is a numpy array with most of the data I need for this plot.
Can you remind me how Dan sums the azimuth and altitude errors to arrive at total error?  With that obstacle clear it shouldn't take me too long to finish the task.

**Comment by liweihung** [comment]
The total error is the sum of individual errors in quadrature. Total error = sqrt(AZ_error**2+ALT_error**2). And the average total error (0.407 in the above example) is just the average of all the points of total error (average of the red points). You might get a slight different number then the above example because the pipeline we are using is new. However, it shouldn't be too far off.

**Comment by dbetchkal** [comment]
@liweihung, I've pushed to _pointing.py_ - let me know what you think?  If the plot is to your satisfaction, feel free to close this issue!

**Comment by liweihung** [comment]
It looks great! I added the cosine factor in the calculation of the error in azimuth: `azmErr = (pErr[1] - pErr[3])*n.cos(n.deg2rad(pErr[4]))` . The cosine factor is needed to account for the shortening of the "latitude" in the sky coordinate as the camera moves towards zenith. Now our number agrees with the old pipeline! 

![pointerr_1](https://user-images.githubusercontent.com/15639514/32513066-330056fe-c3b6-11e7-8bb4-01d7856b53a4.png)
