### ISSUE TITLE
'standards.png' plot

### ISSUE THREAD

**Issue by dbetchkal** [liweihung/nightskies#6]
we briefly discussed altering the _standards.png_ plot during our 10/27/17 meeting, with aims to make the content easier to understand.  revisions included:

- change figure facecolor to black
- change V magnitude of stars to greyscale

**Comment by liweihung** [comment]
I modified the standards.py script and now the script will generate 3 versions of the same plot (I still like the colored one).

![standards_c](https://user-images.githubusercontent.com/15639514/32512482-5bde99ac-c3b4-11e7-89b4-676c6f4d2531.png)
![standards_w](https://user-images.githubusercontent.com/15639514/32512484-5d94bfc4-c3b4-11e7-93f2-c57c6c92249e.png)
![standards_b](https://user-images.githubusercontent.com/15639514/32512487-5f12c63e-c3b4-11e7-97e1-14eeafff482a.png)
